# Generated by Django 5.2.3 on 2025-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка'),
        ),
    ]
